### ISSUE TITLE
BLOB in DB

### ISSUE THREAD

**Issue by ghost** [IFMO-MobDev-2013/extratask1#1]
Is it good idea to store BLOB in the database? Why I cannot save photo in filesystem of my device?

**Comment by thevery** [comment]
you can store images in files and use http://developer.android.com/reference/android/content/ContentResolver.html#openInputStream(android.net.Uri)

**Comment by ghost** [comment]
Thanks

**Comment by ghost** [comment]
I have some quetions about android.
How can I connect my android app to mysql/mssql and other databases?

**Comment by thevery** [comment]
you can probably use jdbc but you don't usually need this

**Comment by ghost** [comment]
But in jdbc username and password are transmitted over the network and anyone can get it

**Comment by thevery** [comment]
so what? the problem is actual for non-android java apps, too.
and you don't need non-sqlite database for this task anyway.

**Comment by ghost** [comment]
ok thanks
