### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by str1t3r** [IFMO-MobDev-2013/extratask1#2]
Результат принимается до воскресенья (20 января) 23:59. ©

20th january is monday, and sunday is 19
what is the right deadline, 20th of january or monday? :)

**Comment by thevery** [comment]
Sunday, 19
16 ÑÎ×. 2014 Ç. 0:36 ÐÏÌØÚÏ×ÁÔÅÌØ "Rakovsky Alexander" <
notifications@github.com> ÎÁÐÉÓÁÌ:
