### ISSUE TITLE
Number picture

### ISSUE THREAD

**Issue by Tenischev** [IFMO-MobDev-2013/extratask1#4]
You write "показываются миниатюры первые 20 фотографий " and next "Список должен отображать 30". 
Please say, how many displayed picture.

**Comment by ghost** [comment]
Я думаю что надо загрузить топ 30 а отображать в списке по 20

**Comment by ghost** [comment]
То есть часть списка надо прокрутить вниз

**Comment by thevery** [comment]
@Tenischev 20 is enough, fixed
@ermakovm list (actually grid) cannot show more than 12 photos on 1 screen anyway
